db:
  image: mariadb:latest
  ports:
    # ext:int port.
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=feedbag
    - MYSQL_ROOT_PASSWORD=feedbag
    - MYSQL_USER=feedbag
    - MYSQL_PASSWORD=feedbag

backend:
  build: backend
  command: python manage.py runserver 0:8000
  # command: uwsgi --ini uwsgi.ini # For production.
  volumes:
    - ./backend:/usr/src/feedbag
  ports:
    # ext:int port.
    - "8005:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
  environment:
    # Use the root user to enable creation of a test database.
    - DATABASE_URL=mysql://root:feedbag@db/feedbag
    - DEBUG=1

frontend:
  build: frontend
  command: gulp
  volumes:
    - ./frontend:/usr/src/frontend
  ports:
    # ext:int port.
    - "3000:3000"
    - "3001:3001"  # Used by browsersync
