db:
  image: mariadb:latest
  environment:
    - MYSQL_DATABASE=feedbag
    - MYSQL_ROOT_PASSWORD=feedbag
    - MYSQL_USER=feedbag
    - MYSQL_PASSWORD=feedbag

backend:
  build: backend
  command: python manage.py runserver 0:8000
  # command: uwsgi --ini uwsgi.ini # For production.
  volumes:
    - ./backend:/usr/src/feedbag
  ports:
    # ext:int port.
    - "8005:8000"
  links:
    # Define all containers for easy running of development setup.
    - db
  environment:
    # Use the root user to enable creation of a test database.
    - DATABASE_URL=mysql://root:feedbag@db/feedbag
    - DEBUG=1
    - CORS_ORIGIN_WHITELIST=localhost:8080
    - SOCIAL_AUTH_GOOGLE_PLUS_KEY=197265624471-f8cb8sdb8dr1uevsscev16191ksr3ln6.apps.googleusercontent.com
    - SOCIAL_AUTH_GOOGLE_PLUS_SECRET=1KDKrqdje9S5zWXKiGlAoRgb
    - SOCIAL_AUTH_GOOGLE_PLUS_WHITELISTED_DOMAINS=wearespindle.com


frontend:
  build: frontend
  command: gulp
  volumes:
    - ./frontend:/usr/src/frontend
  ports:
    # ext:int port.
    - "8080:8080"
