version: '2.0'

services:

  backend:
    build: backend
    command: uwsgi --ini uwsgi.ini --static-map /static=/usr/src/flindt/flindt/static # For production.
    volumes:
      - ./backend:/usr/src/flindt
    ports:
      # ext:int port.
      - "127.0.0.1:8005:8000"

  proxy:
    build: backend/proxy
    command: --api # the Web UI
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080" # the Web UI
